[profile.default]
src = 'contracts'
out = 'forge/out'
libs = ["dependencies"]
test = 'test/forge'
cache_path  = 'forge/cache'
solc = "0.8.27"
ignored_warnings_from = ["dependencies"]
dynamic_test_linking = true
remappings = [
  "forge-std/=dependencies/forge-std-1.11.0/src/",
  "capo/=dependencies/woof-software-compound-capo-lst-lrt-oracles/",
  "oz/=dependencies/@openzeppelin-contracts-5.5.0/",
  # For Aria dependency
  "openzeppelin-contracts/=dependencies/@openzeppelin-contracts-5.5.0/",
  "aria/=dependencies/aria-v1.1.0/contracts/"
]
via_ir = true
optimizer = true
optimizer_runs = 1
evm_version = "cancun"

[profile.default.optimizer_details.yul_details]
optimizerSteps = "dhfoDgvulfnTUtnIf [xa[r]scLM cCTUtTOntnfDIul Lcul Vcul [j] Tpeul xa[rul] xa[r]cL gvif CTUca[r]LsTOtfDnca[r]Iulc] jmul[jul] VcTOcul jmul"

[profile.ci]
verbosity = 4
libs = ["dependencies"]
# disable for CI (used for debugging liquidity issues)
no_match_test = "test.*SwapVia"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'preserve'
func_attrs_with_params_multiline = false
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'
multiline_func_header= 'attributes_first'
ignore = ["contracts/"]

[soldeer]
remappings_location = "config"

[dependencies]
forge-std = "1.11.0"
"woof-software/compound-capo" = { version = "lst-lrt-oracles", git = "git@github.com:woof-software/compound-capo.git", branch = "lst-lrt-oracles" }
aria = { version = "v1.1.0", git = "git@github.com:AriaProtocol/main-contracts.git", branch = "main" }
"@openzeppelin-contracts" = "5.5.0"
